import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/customUI/navbar';
import Footer from '@/components/customUI/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Ninkaj Electronics',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}, overflow-x-hidden lg`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
